language: node_js

node_js:
  - stable

script: bash ./deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "cb2980a4587d"
    - COMMIT_AUTHOR_EMAIL: "clarkenciel@gmail.com"

before_install:
- openssl aes-256-cbc -K $encrypted_cb2980a4587d_key -iv $encrypted_cb2980a4587d_iv
  -in deploy_key.enc -out deploy_key -d
